#!/bin/bash

set -ex

aws_cpi_dir=$(cd $(dirname $0)/../ && pwd)
aws_cpi_gems_dir=$aws_cpi_dir/src/bosh_aws_cpi

cleanup() {
  cd $aws_cpi_gems_dir
  rm -rf Gemfile*
}

trap cleanup EXIT

if [ ! -d $aws_cpi_gems_dir ]; then
  mkdir $aws_cpi_gems_dir
fi

(
  cd $aws_cpi_gems_dir
  cat > 'Gemfile' <<EOF
source "https://rubygems.org"

gem "bosh_aws_cpi"
EOF

  bundle package
)
